version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root           
      MYSQL_DATABASE: tickets            
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 5

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: nest-server
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USERNAME: root                     
      DB_PASSWORD: root                     
      DB_NAME: tickets                      
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: vue-client
    environment:
      VITE_API_URL: http://server:3000
    ports:
      - "5173:80"
    depends_on:
      - server
    networks:
      - app-network

volumes:
  db_data: {}

networks:
  app-network: {}
